export const MajorAreasOfPakistan = [
  { value: "Karachi", label: "Karachi" },
  { value: "Hyderabad", label: "Hyderabad" },
  { value: "Sukkur", label: "Sukkur" },
  { value: "Larkana", label: "Larkana" },
  { value: "Mirpur Khas", label: "Mirpur Khas" },
  { value: "Nawabshah", label: "Nawabshah" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Thatta", label: "Thatta" },
  { value: "Dadu", label: "Dadu" },
  { value: "Jacobabad", label: "Jacobabad" },
  { value: "Shikarpur", label: "Shikarpur" },
  { value: "Sanghar", label: "Sanghar" },
  { value: "Ghotki", label: "Ghotki" },
  { value: "Umerkot", label: "Umerkot" },
  { value: "Tando Allahyar", label: "Tando Allahyar" },
  { value: "Badin", label: "Badin" },
  { value: "Kotri", label: "Kotri" },
  { value: "Matiari", label: "Matiari" },
  { value: "Tando Adam", label: "Tando Adam" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Moro", label: "Moro" },
  { value: "Kandhkot", label: "Kandhkot" },
  { value: "Daharki", label: "Daharki" },
  { value: "Rohri", label: "Rohri" },
  { value: "Jamshoro", label: "Jamshoro" },
  { value: "Mithi", label: "Mithi" },
  { value: "Hala", label: "Hala" },
  { value: "Sehwan", label: "Sehwan" },
  { value: "Naudero", label: "Naudero" },
  { value: "Warah", label: "Warah" },
  { value: "Ranipur", label: "Ranipur" },
  { value: "Kamber", label: "Kamber" },
  { value: "Rohri", label: "Rohri" },
  { value: "Meerwah", label: "Meerwah" },
  { value: "Dokri", label: "Dokri" },
  { value: "Tando Muhammad Khan", label: "Tando Muhammad Khan" },
  { value: "Moro", label: "Moro" },
  { value: "Digri", label: "Digri" },
  { value: "Qambar", label: "Qambar" },
  { value: "Wahi Pandhi", label: "Wahi Pandhi" },
  { value: "Khipro", label: "Khipro" },
  { value: "Sakrand", label: "Sakrand" },
  { value: "Mehrabpur", label: "Mehrabpur" },
  { value: "Khanpur", label: "Khanpur" },
  { value: "Matiari", label: "Matiari" },
  { value: "Nawabshah", label: "Nawabshah" },
  { value: "Jhol", label: "Jhol" },
  { value: "Shahdadpur", label: "Shahdadpur" },
  { value: "Sinjhoro", label: "Sinjhoro" },
  { value: "Khipro", label: "Khipro" },
  { value: "Thari Mirwah", label: "Thari Mirwah" },
  { value: "Tando Bago", label: "Tando Bago" },
  { value: "Rohri", label: "Rohri" },
  { value: "Kashmore", label: "Kashmore" },
  { value: "Ghari Khairo", label: "Ghari Khairo" },
  { value: "Madeji", label: "Madeji" },
  { value: "Tangwani", label: "Tangwani" },
  { value: "Sobho Dero", label: "Sobho Dero" },
  { value: "Lakhi", label: "Lakhi" },
  { value: "Qubo Saeed Khan", label: "Qubo Saeed Khan" },
  { value: "Daur", label: "Daur" },
  { value: "Bhiria", label: "Bhiria" },
  { value: "Mehar", label: "Mehar" },
  { value: "Bhiria Road", label: "Bhiria Road" },
  { value: "Hala New", label: "Hala New" },
  { value: "Jhudo", label: "Jhudo" },
  { value: "Sindhri", label: "Sindhri" },
  { value: "Bakrani", label: "Bakrani" },
  { value: "Samaro", label: "Samaro" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Therhi", label: "Therhi" },
  { value: "Nasirabad", label: "Nasirabad" },
  { value: "Matiari", label: "Matiari" },
  { value: "Tharu Shah", label: "Tharu Shah" },
  { value: "Bela", label: "Bela" },
  { value: "New Saeedabad", label: "New Saeedabad" },
  { value: "Rajo Khanani", label: "Rajo Khanani" },
  { value: "Bhan", label: "Bhan" },
  { value: "Pir jo Goth", label: "Pir jo Goth" },
  { value: "Tando Ghulam Ali", label: "Tando Ghulam Ali" },
  { value: "Chuhar Jamali", label: "Chuhar Jamali" },
  { value: "Nabisar", label: "Nabisar" },
  { value: "Daur", label: "Daur" },
  { value: "Daulatpur", label: "Daulatpur" },
  { value: "Nara", label: "Nara" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Dokri", label: "Dokri" },
  { value: "Thul", label: "Thul" },
  { value: "Meeranpur", label: "Meeranpur" },
  { value: "Gambat", label: "Gambat" },
  { value: "Kingri", label: "Kingri" },
  { value: "Sijawal Junejo", label: "Sijawal Junejo" },
  { value: "Naudero", label: "Naudero" },
  { value: "Garhi Yasin", label: "Garhi Yasin" },
  { value: "Sobhodero", label: "Sobhodero" },
  { value: "Sukrand", label: "Sukrand" },
  { value: "Bhit Shah", label: "Bhit Shah" },
  { value: "Tharu Shah", label: "Tharu Shah" },
  { value: "New Badah", label: "New Badah" },
  { value: "Bakhri", label: "Bakhri" },
  { value: "Rohri", label: "Rohri" },
  { value: "Nasirabad", label: "Nasirabad" },
  { value: "Bhan", label: "Bhan" },
  { value: "Pir jo Goth", label: "Pir jo Goth" },
  { value: "Tando Ghulam Ali", label: "Tando Ghulam Ali" },
  { value: "Chuhar Jamali", label: "Chuhar Jamali" },
  { value: "Nabisar", label: "Nabisar" },
  { value: "Daur", label: "Daur" },
  { value: "Daulatpur", label: "Daulatpur" },
  { value: "Nara", label: "Nara" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Dokri", label: "Dokri" },
  { value: "Thul", label: "Thul" },
  { value: "Meeranpur", label: "Meeranpur" },
  { value: "Gambat", label: "Gambat" },
  { value: "Kingri", label: "Kingri" },
  { value: "Sijawal Junejo", label: "Sijawal Junejo" },
  { value: "Naudero", label: "Naudero" },
  { value: "Garhi Yasin", label: "Garhi Yasin" },
  { value: "Sobhodero", label: "Sobhodero" },
  { value: "Peshawar", label: "Peshawar" },
  { value: "Mardan", label: "Mardan" },
  { value: "Swat", label: "Swat" },
  { value: "Abbottabad", label: "Abbottabad" },
  { value: "Nowshera", label: "Nowshera" },
  { value: "Mansehra", label: "Mansehra" },
  { value: "Dera Ismail Khan", label: "Dera Ismail Khan" },
  { value: "Charsadda", label: "Charsadda" },
  { value: "Kohat", label: "Kohat" },
  { value: "Haripur", label: "Haripur" },
  { value: "Bannu", label: "Bannu" },
  { value: "Chitral", label: "Chitral" },
  { value: "Batagram", label: "Batagram" },
  { value: "Tank", label: "Tank" },
  { value: "Dir", label: "Dir" },
  { value: "Hangu", label: "Hangu" },
  { value: "Shangla", label: "Shangla" },
  { value: "Karak", label: "Karak" },
  { value: "Swabi", label: "Swabi" },
  { value: "Upper Dir", label: "Upper Dir" },
  { value: "Lower Dir", label: "Lower Dir" },
  { value: "Khanewal", label: "Khanewal" },
  { value: "Lakki Marwat", label: "Lakki Marwat" },
  { value: "Kohistan", label: "Kohistan" },
  { value: "Buner", label: "Buner" },
  { value: "Malakand", label: "Malakand" },
  { value: "Shabqadar", label: "Shabqadar" },
  { value: "Mingora", label: "Mingora" },
  { value: "Charsadda", label: "Charsadda" },
  { value: "Kabal", label: "Kabal" },
  { value: "Topi", label: "Topi" },
  { value: "Alpuri", label: "Alpuri" },
  { value: "Rustam", label: "Rustam" },
  { value: "Parachinar", label: "Parachinar" },
  { value: "Thana", label: "Thana" },
  { value: "Daggar", label: "Daggar" },
  { value: "Pabbi", label: "Pabbi" },
  { value: "Risalpur", label: "Risalpur" },
  { value: "Bakhshali", label: "Bakhshali" },
  { value: "Bela", label: "Bela" },
  { value: "Chakdara", label: "Chakdara" },
  { value: "Chakku", label: "Chakku" },
  { value: "Charsadda", label: "Charsadda" },
  { value: "Chitral", label: "Chitral" },
  { value: "Daggar", label: "Daggar" },
  { value: "Dargai", label: "Dargai" },
  { value: "Dera Ismail Khan", label: "Dera Ismail Khan" },
  { value: "Dir", label: "Dir" },
  { value: "Drosh", label: "Drosh" },
  { value: "Haripur", label: "Haripur" },
  { value: "Karak", label: "Karak" },
  { value: "Kohat", label: "Kohat" },
  { value: "Lakki Marwat", label: "Lakki Marwat" },
  { value: "Lower Dir", label: "Lower Dir" },
  { value: "Malakand", label: "Malakand" },
  { value: "Mansehra", label: "Mansehra" },
  { value: "Mardan", label: "Mardan" },
  { value: "Mingora", label: "Mingora" },
  { value: "Nowshera", label: "Nowshera" },
  { value: "Paharpur", label: "Paharpur" },
  { value: "Peshawar", label: "Peshawar" },
  { value: "Rustam", label: "Rustam" },
  { value: "Shabqadar", label: "Shabqadar" },
  { value: "Shangla", label: "Shangla" },
  { value: "Swabi", label: "Swabi" },
  { value: "Swat", label: "Swat" },
  { value: "Tank", label: "Tank" },
  { value: "Thana", label: "Thana" },
  { value: "Topi", label: "Topi" },
  { value: "Upper Dir", label: "Upper Dir" },
  { value: "Bhit Shah", label: "Bhit Shah" },
  { value: "Tharu Shah", label: "Tharu Shah" },
  { value: "New Badah", label: "New Badah" },
  { value: "Bakhri", label: "Bakhri" },
  { value: "Quetta", label: "Quetta" },
  { value: "Gwadar", label: "Gwadar" },
  { value: "Chaman", label: "Chaman" },
  { value: "Turbat", label: "Turbat" },
  { value: "Khuzdar", label: "Khuzdar" },
  { value: "Sibi", label: "Sibi" },
  { value: "Zhob", label: "Zhob" },
  { value: "Loralai", label: "Loralai" },
  { value: "Dera Bugti", label: "Dera Bugti" },
  { value: "Nushki", label: "Nushki" },
  { value: "Mastung", label: "Mastung" },
  { value: "Kharan", label: "Kharan" },
  { value: "Panjgur", label: "Panjgur" },
  { value: "Kalat", label: "Kalat" },
  { value: "Mach", label: "Mach" },
  { value: "Awaran", label: "Awaran" },
  { value: "Qila Abdullah", label: "Qila Abdullah" },
  { value: "Ormara", label: "Ormara" },
  { value: "Pasni", label: "Pasni" },
  { value: "Kohlu", label: "Kohlu" },
  { value: "Dalbandin", label: "Dalbandin" },
  { value: "Wadh", label: "Wadh" },
  { value: "Dera Murad Jamali", label: "Dera Murad Jamali" },
  { value: "Bela", label: "Bela" },
  { value: "Kech", label: "Kech" },
  { value: "Sui", label: "Sui" },
  { value: "Gandava", label: "Gandava" },
  { value: "Chagai", label: "Chagai" },
  { value: "Harnai", label: "Harnai" },
  { value: "Khuzdar", label: "Khuzdar" },
  { value: "Lasbela", label: "Lasbela" },
  { value: "Makran", label: "Makran" },
  { value: "Mangochar", label: "Mangochar" },
  { value: "Mekhtar", label: "Mekhtar" },
  { value: "Pishin", label: "Pishin" },
  { value: "Killa Saifullah", label: "Killa Saifullah" },
  { value: "Musa Khel Bazar", label: "Musa Khel Bazar" },
  { value: "Killa Abdullah", label: "Killa Abdullah" },
  { value: "Barkhan", label: "Barkhan" },
  { value: "Sherani", label: "Sherani" },
  { value: "Lehri", label: "Lehri" },
  { value: "Nasirabad", label: "Nasirabad" },
  { value: "Chaman", label: "Chaman" },
  { value: "Taftan", label: "Taftan" },
  { value: "Mand", label: "Mand" },
  { value: "Tump", label: "Tump" },
  { value: "Turbat", label: "Turbat" },
  { value: "Gwadar", label: "Gwadar" },
  { value: "Pasni", label: "Pasni" },
  { value: "Ormara", label: "Ormara" },
  { value: "Jiwani", label: "Jiwani" },
  { value: "Gaddani", label: "Gaddani" },
  { value: "Hub", label: "Hub" },
  { value: "Winder", label: "Winder" },
  { value: "Uthal", label: "Uthal" },
  { value: "Mach", label: "Mach" },
  { value: "Dera Allah Yar", label: "Dera Allah Yar" },
  { value: "Jaffarabad", label: "Jaffarabad" },
  { value: "Jhal Magsi", label: "Jhal Magsi" },
  { value: "Khuzdar", label: "Khuzdar" },
  { value: "Kalat", label: "Kalat" },
  { value: "Ziarat", label: "Ziarat" },
  { value: "Hanna Lake", label: "Hanna Lake" },
  { value: "Urak Valley", label: "Urak Valley" },
  { value: "Bolan Pass", label: "Bolan Pass" },
  { value: "Gaddani Beach", label: "Gaddani Beach" },
  { value: "Hingol National Park", label: "Hingol National Park" },
  { value: "Astola Island", label: "Astola Island" },
  { value: "Bela", label: "Bela" },
  { value: "New Saeedabad", label: "New Saeedabad" },
  { value: "Rajo Khanani", label: "Rajo Khanani" },
  { value: "Bhan", label: "Bhan" },
  { value: "Pir jo Goth", label: "Pir jo Goth" },
  { value: "Tando Ghulam Ali", label: "Tando Ghulam Ali" },
  { value: "Chuhar Jamali", label: "Chuhar Jamali" },
  { value: "Nabisar", label: "Nabisar" },
  { value: "Daur", label: "Daur" },
  { value: "Daulatpur", label: "Daulatpur" },
  { value: "Nara", label: "Nara" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Dokri", label: "Dokri" },
  { value: "Thul", label: "Thul" },
  { value: "Meeranpur", label: "Meeranpur" },
  { value: "Gambat", label: "Gambat" },
  { value: "Kingri", label: "Kingri" },
  { value: "Sijawal Junejo", label: "Sijawal Junejo" },
  { value: "Naudero", label: "Naudero" },
  { value: "Garhi Yasin", label: "Garhi Yasin" },
  { value: "Sobhodero", label: "Sobhodero" },

  { value: "Bhit Shah", label: "Bhit Shah" },
  { value: "Tharu Shah", label: "Tharu Shah" },
  { value: "New Badah", label: "New Badah" },
  { value: "Bakhri", label: "Bakhri" },
  { value: "Rohri", label: "Rohri" },
  { value: "Nasirabad", label: "Nasirabad" },
  { value: "Bhan", label: "Bhan" },
  { value: "Pir jo Goth", label: "Pir jo Goth" },
  { value: "Tando Ghulam Ali", label: "Tando Ghulam Ali" },
  { value: "Chuhar Jamali", label: "Chuhar Jamali" },
  { value: "Nabisar", label: "Nabisar" },
  { value: "Daur", label: "Daur" },
  { value: "Daulatpur", label: "Daulatpur" },
  { value: "Nara", label: "Nara" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Dokri", label: "Dokri" },
  { value: "Thul", label: "Thul" },
  { value: "Meeranpur", label: "Meeranpur" },
  { value: "Gambat", label: "Gambat" },
  { value: "Kingri", label: "Kingri" },
  { value: "Sijawal Junejo", label: "Sijawal Junejo" },
  { value: "Naudero", label: "Naudero" },
  { value: "Garhi Yasin", label: "Garhi Yasin" },
  { value: "Sobhodero", label: "Sobhodero" },

  { value: "Bhit Shah", label: "Bhit Shah" },
  { value: "Tharu Shah", label: "Tharu Shah" },
  { value: "New Badah", label: "New Badah" },
  { value: "Bakhri", label: "Bakhri" },
  { value: "Rohri", label: "Rohri" },
  { value: "Nasirabad", label: "Nasirabad" },
  { value: "Bhan", label: "Bhan" },
  { value: "Pir jo Goth", label: "Pir jo Goth" },
  { value: "Tando Ghulam Ali", label: "Tando Ghulam Ali" },
  { value: "Chuhar Jamali", label: "Chuhar Jamali" },
  { value: "Nabisar", label: "Nabisar" },
  { value: "Daur", label: "Daur" },
  { value: "Daulatpur", label: "Daulatpur" },
  { value: "Nara", label: "Nara" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Dokri", label: "Dokri" },
  { value: "Thul", label: "Thul" },
  { value: "Meeranpur", label: "Meeranpur" },
  { value: "Gambat", label: "Gambat" },
  { value: "Kingri", label: "Kingri" },
  { value: "Sijawal Junejo", label: "Sijawal Junejo" },
  { value: "Naudero", label: "Naudero" },
  { value: "Garhi Yasin", label: "Garhi Yasin" },
  { value: "Sobhodero", label: "Sobhodero" },

  { value: "Bhit Shah", label: "Bhit Shah" },
  { value: "Tharu Shah", label: "Tharu Shah" },
  { value: "New Badah", label: "New Badah" },
  { value: "Bakhri", label: "Bakhri" },
  { value: "Rohri", label: "Rohri" },
  { value: "Nasirabad", label: "Nasirabad" },
  { value: "Bhan", label: "Bhan" },
  { value: "Pir jo Goth", label: "Pir jo Goth" },
  { value: "Tando Ghulam Ali", label: "Tando Ghulam Ali" },
  { value: "Chuhar Jamali", label: "Chuhar Jamali" },
  { value: "Nabisar", label: "Nabisar" },
  { value: "Daur", label: "Daur" },
  { value: "Daulatpur", label: "Daulatpur" },
  { value: "Nara", label: "Nara" },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Ratodero", label: "Ratodero" },
  { value: "Dokri", label: "Dokri" },
  { value: "Thul", label: "Thul" },
  { value: "Meeranpur", label: "Meeranpur" },
  { value: "Gambat", label: "Gambat" },
  { value: "Kingri", label: "Kingri" },
  { value: "Sijawal Junejo", label: "Sijawal Junejo" },
  { value: "Naudero", label: "Naudero" },
  { value: "Garhi Yasin", label: "Garhi Yasin" },
  { value: "Sobhodero", label: "Sobhodero" },

  { value: "Bhit Shah", label: "Bhit Shah" },
  { value: "Tharu Shah", label: "Tharu Shah" },
  { value: "New Badah", label: "New Badah" },
  { value: "Bakhri", label: "Bakhri" },
  { value: "Rohri", label: "Rohri" },
  { value: "Nasirabad", label: "Nasirabad" },
  { value: "Lahore", label: "Lahore" },
  { value: "Faisalabad", label: "Faisalabad" },
  { value: "Rawalpindi", label: "Rawalpindi" },
  { value: "Multan", label: "Multan" },
  { value: "Gujranwala", label: "Gujranwala" },
  { value: "Sialkot", label: "Sialkot" },
  { value: "Bahawalpur", label: "Bahawalpur" },
  { value: "Sargodha", label: "Sargodha" },
  { value: "Gujrat", label: "Gujrat" },
  { value: "Jhelum", label: "Jhelum" },
  { value: "Sahiwal", label: "Sahiwal" },
  { value: "Okara", label: "Okara" },
  { value: "Sheikhupura", label: "Sheikhupura" },
  { value: "Chiniot", label: "Chiniot" },
  { value: "Mandi Bahauddin", label: "Mandi Bahauddin" },
  { value: "Sadiqabad", label: "Sadiqabad" },
  { value: "Kasur", label: "Kasur" },
  { value: "Muzaffargarh", label: "Muzaffargarh" },
  { value: "Rahim Yar Khan", label: "Rahim Yar Khan" },
  { value: "Pakpattan", label: "Pakpattan" },
  { value: "Dera Ghazi Khan", label: "Dera Ghazi Khan" },
  { value: "Narowal", label: "Narowal" },
  { value: "Jhang", label: "Jhang" },
  { value: "Attock", label: "Attock" },
  { value: "Layyah", label: "Layyah" },
  { value: "Bhakkar", label: "Bhakkar" },
  { value: "Khushab", label: "Khushab" },
  { value: "Chakwal", label: "Chakwal" },
  { value: "Vehari", label: "Vehari" },
  { value: "Hafizabad", label: "Hafizabad" },
  { value: "Mianwali", label: "Mianwali" },
  { value: "Khanewal", label: "Khanewal" },
  { value: "Toba Tek Singh", label: "Toba Tek Singh" },
  { value: "Nankana Sahib", label: "Nankana Sahib" },
  { value: "Rajanpur", label: "Rajanpur" },
  { value: "Burewala", label: "Burewala" },
  { value: "Gojra", label: "Gojra" },
  { value: "Muridke", label: "Muridke" },
  { value: "Kamalia", label: "Kamalia" },
  { value: "Ahmedpur East", label: "Ahmedpur East" },
  { value: "Tando Allahyar", label: "Tando Allahyar" },
  { value: "Vihari", label: "Vihari" },
  { value: "Hasilpur", label: "Hasilpur" },
  { value: "Kahna Nau", label: "Kahna Nau" },
  { value: "Chichawatni", label: "Chichawatni" },
  { value: "Kamoke", label: "Kamoke" },
  { value: "Mian Channu", label: "Mian Channu" },
  { value: "Murree", label: "Murree" },
  { value: "Shakargarh", label: "Shakargarh" },
  { value: "Kot Addu", label: "Kot Addu" },
  { value: "Lodhran", label: "Lodhran" },
  { value: "Kharian", label: "Kharian" },
  { value: "Jaranwala", label: "Jaranwala" },
  { value: "Wazirabad", label: "Wazirabad" },
  { value: "Mailsi", label: "Mailsi" },
  { value: "Arifwala", label: "Arifwala" },
  { value: "Sambrial", label: "Sambrial" },
  { value: "Talagang", label: "Talagang" },
  { value: "Kahror Pakka", label: "Kahror Pakka" },
  { value: "Fort Abbas", label: "Fort Abbas" },
  { value: "Malakwal", label: "Malakwal" },
  { value: "Tandlianwala", label: "Tandlianwala" },
  { value: "Pind Dadan Khan", label: "Pind Dadan Khan" },
  { value: "Kanganpur", label: "Kanganpur" },
  { value: "Shujaabad", label: "Shujaabad" },
  { value: "Bhalwal", label: "Bhalwal" },
  { value: "Pir Mahal", label: "Pir Mahal" },
  { value: "Bhawana", label: "Bhawana" },
  { value: "Jampur", label: "Jampur" },
  { value: "Kot Mithan", label: "Kot Mithan" },
  { value: "Pattoki", label: "Pattoki" },
  { value: "Renala Khurd", label: "Renala Khurd" },
  { value: "Kunjah", label: "Kunjah" },
  { value: "Choa Saidan Shah", label: "Choa Saidan Shah" },
  { value: "Daska", label: "Daska" },
  { value: "Hazro", label: "Hazro" },
  { value: "Bhakkar", label: "Bhakkar" },
  { value: "Dunyapur", label: "Dunyapur" },
  { value: "Kot Radha Kishan", label: "Kot Radha Kishan" },
  { value: "Chak Jhumra", label: "Chak Jhumra" },
  { value: "Qadirabad", label: "Qadirabad" },
  { value: "Kamra", label: "Kamra" },
  { value: "Kahuta", label: "Kahuta" },
  { value: "Kahror Lal Essan", label: "Kahror Lal Essan" },
  { value: "Kanganpur", label: "Kanganpur" },
  { value: "Lala Musa", label: "Lala Musa" },
  { value: "Malakwal", label: "Malakwal" },
  { value: "Minchinabad", label: "Minchinabad" },
  { value: "Mitha Tiwana", label: "Mitha Tiwana" },
  { value: "Monga", label: "Monga" },
  { value: "Mubarikpur", label: "Mubarikpur" },
  { value: "Nankana Sahib", label: "Nankana Sahib" },
  { value: "Pasrur", label: "Pasrur" },
  { value: "Raiwind", label: "Raiwind" },
  { value: "Sambrial", label: "Sambrial" },
  { value: "Shorkot", label: "Shorkot" },
  { value: "Sohawa", label: "Sohawa" },
  { value: "Tandlianwala", label: "Tandlianwala" },
  { value: "Tarogil", label: "Tarogil" },
  { value: "Ugoke", label: "Ugoke" },
  { value: "Wah", label: "Wah" },
  { value: "Wazirabad", label: "Wazirabad" },
  { value: "Zafarwal", label: "Zafarwal" },
  { value: "Gujar Khan", label: "Gujar Khan" },
  { value: "Haveli Lakha", label: "Haveli Lakha" },
  { value: "Jalalpur Pirwala", label: "Jalalpur Pirwala" },
  { value: "Kallar Kahar", label: "Kallar Kahar" },
  { value: "Kamalia", label: "Kamalia" },
  { value: "Kharian", label: "Kharian" },
  { value: "Kot Momin", label: "Kot Momin" },
  { value: "Kundian", label: "Kundian" },
  { value: "Lalian", label: "Lalian" },
  { value: "Liaqatpur", label: "Liaqatpur" },
  { value: "Mamukanjan", label: "Mamukanjan" },
  { value: "Mandi Bahauddin", label: "Mandi Bahauddin" },
  { value: "Mianwali", label: "Mianwali" },
  { value: "Qila Didar Singh", label: "Qila Didar Singh" },
  { value: "Raiwind", label: "Raiwind" },
  { value: "Ratwal", label: "Ratwal" },
  { value: "Renala Khurd", label: "Renala Khurd" },
  { value: "Sangla Hill", label: "Sangla Hill" },
  { value: "Shahkot", label: "Shahkot" },
  { value: "Shakargarh", label: "Shakargarh" },
  { value: "Shamsabad", label: "Shamsabad" },
  { value: "Shorkot", label: "Shorkot" },
  { value: "Sillanwali", label: "Sillanwali" },
  { value: "Tandlianwala", label: "Tandlianwala" },
  { value: "Wah Cantt", label: "Wah Cantt" },
  { value: "Bhera", label: "Bhera" },
  { value: "Chunian", label: "Chunian" },
  { value: "Darya Khan", label: "Darya Khan" },
  { value: "Fort Abbas", label: "Fort Abbas" },
  { value: "Haroonabad", label: "Haroonabad" },
  { value: "Jand", label: "Jand" },
  { value: "Jatoi", label: "Jatoi" },
  { value: "Kahna", label: "Kahna" },
  { value: "Kahuta", label: "Kahuta" },
  { value: "Kallar Syedan", label: "Kallar Syedan" },
  { value: "Kamoke", label: "Kamoke" },
  { value: "Kot Sultan", label: "Kot Sultan" },
  { value: "Lalamusa", label: "Lalamusa" },
  { value: "Liaquatpur", label: "Liaquatpur" },
  { value: "Mailsi", label: "Mailsi" },
  { value: "Malakwal", label: "Malakwal" },
  { value: "Mandi Bahauddin", label: "Mandi Bahauddin" },
  { value: "Mian Channu", label: "Mian Channu" },
  { value: "Mianwali", label: "Mianwali" },
  { value: "Nowshera Virkan", label: "Nowshera Virkan" },
  { value: "Pindi Bhattian", label: "Pindi Bhattian" },
  { value: "Pir Mahal", label: "Pir Mahal" },
  { value: "Rabwah", label: "Rabwah" },
  { value: "Rajanpur", label: "Rajanpur" },
  { value: "Ratwal", label: "Ratwal" },
  { value: "Sadiqabad", label: "Sadiqabad" },
  { value: "Sarai Alamgir", label: "Sarai Alamgir" },
  { value: "Shakargarh", label: "Shakargarh" },
  { value: "Sharaqpur", label: "Sharaqpur" },
  { value: "Sheikhupura", label: "Sheikhupura" },
  { value: "Sodhra", label: "Sodhra" },
  { value: "Taunsa", label: "Taunsa" },
  { value: "Thatta Ghulamka Dheroka", label: "Thatta Ghulamka Dheroka" },
  { value: "Tibba Sultanpur", label: "Tibba Sultanpur" },
  { value: "F-6", label: "F-6" },
  { value: "F-7", label: "F-7" },
  { value: "F-8", label: "F-8" },
  { value: "F-9", label: "F-9" },
  { value: "F-10", label: "F-10" },
  { value: "F-11", label: "F-11" },
  { value: "G-5", label: "G-5" },
  { value: "G-6", label: "G-6" },
  { value: "G-7", label: "G-7" },
  { value: "G-8", label: "G-8" },
  { value: "G-9", label: "G-9" },
  { value: "G-10", label: "G-10" },
  { value: "G-11", label: "G-11" },
  { value: "G-12", label: "G-12" },
  { value: "H-8", label: "H-8" },
  { value: "H-9", label: "H-9" },
  { value: "H-10", label: "H-10" },
  { value: "I-8", label: "I-8" },
  { value: "I-9", label: "I-9" },
  { value: "I-10", label: "I-10" },
  { value: "I-11", label: "I-11" },
  { value: "E-7", label: "E-7" },
  { value: "E-8", label: "E-8" },
  { value: "E-9", label: "E-9" },
  { value: "E-10", label: "E-10" },
  { value: "E-11", label: "E-11" },
  { value: "F-5", label: "F-5" },
  { value: "G-13", label: "G-13" },
  { value: "G-14", label: "G-14" },
  { value: "G-15", label: "G-15" },
  { value: "G-16", label: "G-16" },
  { value: "G-17", label: "G-17" },
  { value: "H-11", label: "H-11" },
  { value: "H-12", label: "H-12" },
  { value: "H-13", label: "H-13" },
  { value: "H-14", label: "H-14" },
  { value: "I-12", label: "I-12" },
  { value: "I-13", label: "I-13" },
  { value: "I-14", label: "I-14" },
  { value: "I-15", label: "I-15" },
  { value: "I-16", label: "I-16" },
  { value: "I-17", label: "I-17" },
  { value: "I-18", label: "I-18" },
  { value: "D-12", label: "D-12" },
  { value: "D-13", label: "D-13" },
  { value: "D-14", label: "D-14" },
  { value: "E-6", label: "E-6" },
  { value: "E-12", label: "E-12" },
  { value: "E-13", label: "E-13" },
  { value: "E-14", label: "E-14" },
  { value: "F-12", label: "F-12" },
  { value: "F-13", label: "F-13" },
  { value: "F-14", label: "F-14" },
  { value: "G-18", label: "G-18" },
  { value: "H-15", label: "H-15" },
  { value: "H-16", label: "H-16" },
  { value: "H-17", label: "H-17" },
  { value: "I-19", label: "I-19" },
  { value: "I-20", label: "I-20" },
  { value: "I-21", label: "I-21" },
];
