const areas = [
    { value: 'Shahdara', label: 'Shahdara' },
    { value: 'Harbanspura', label: 'Harbanspura' },
    { value: 'Nishtar Town', label: 'Nishtar Town' },
    { value: 'Gulberg', label: 'Gulberg' },
    { value: 'Model Town', label: 'Model Town' },
    { value: 'Faisal Town', label: 'Faisal Town' },
    { value: 'Ravi Town', label: 'Ravi Town' },
    { value: 'Aziz Bhatti Town', label: 'Aziz Bhatti Town' },
    { value: 'Data Gunj Buksh Town', label: 'Data Gunj Buksh Town' },
    { value: 'Walled City', label: 'Walled City' },
    { value: 'Shalimar', label: 'Shalimar' },
    { value: 'Wagah', label: 'Wagah' },
    { value: 'Lahore Cantt', label: 'Lahore Cantt' },
    { value: 'Raiwind', label: 'Raiwind' },
    { value: 'Township', label: 'Township' },
    { value: 'Samanabad', label: 'Samanabad' },
    { value: 'Iqbal Town', label: 'Iqbal Town' },
    { value: 'Green Town', label: 'Green Town' },
    { value: 'Sabzazar', label: 'Sabzazar' },
    { value: 'Johar Town', label: 'Johar Town' },
    { value: 'Wapda Town', label: 'Wapda Town' },
    { value: 'Shadman', label: 'Shadman' },
    { value: 'Kot Lakhpat', label: 'Kot Lakhpat' },
    { value: 'Ichra', label: 'Ichra' },
    { value: 'Barki', label: 'Barki' },
    { value: 'Bedian Road', label: 'Bedian Road' },
    { value: 'Kahna Nau', label: 'Kahna Nau' },
    { value: 'DHA Phase 1', label: 'DHA Phase 1' },
    { value: 'Nishtar Colony', label: 'Nishtar Colony' },
    { value: 'Garden Town', label: 'Garden Town' },
    { value: 'Sui Gas Housing Society', label: 'Sui Gas Housing Society' },
    { value: 'Punjab University', label: 'Punjab University' },
    { value: 'Wahdat Colony', label: 'Wahdat Colony' },
    { value: 'Lahore Airport', label: 'Lahore Airport' },
    { value: 'Gulshan-e-Ravi', label: 'Gulshan-e-Ravi' },
    { value: 'Baghbanpura', label: 'Baghbanpura' },
    { value: 'Jallo Park', label: 'Jallo Park' },
    { value: 'Shah Kamal', label: 'Shah Kamal' },
    { value: 'Raiwind Road', label: 'Raiwind Road' },
    { value: 'Thokar Niaz Baig', label: 'Thokar Niaz Baig' },
    { value: 'Multan Road', label: 'Multan Road' },
    { value: 'Chung', label: 'Chung' }
  ];
  
  const AssemblyOptions = [
    { value: "national", label: "National Assembly" },
    { value: "punjab", label: "Punjab Assembly" },
    { value: "sindh", label: "Sindh Assembly" },
    { value: "kpk", label: "KPK Assembly" },
    { value: "balochistan", label: "Balochistan Assembly" },
    // Add more options as needed
  ];
  export { areas, AssemblyOptions };
  